version: '3'

services:
  challenge-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    volumes:
      - ./src/flag.txt:/challengeStore/flag.txt
      - ./src/ChristmasStore:/challengeStore/ChristmasStore
    restart: always
