version: '3'

services:
  challenge-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1340:1340"
    volumes:
      - ./src/flag.txt:/flag.txt
      - ./src/bofbegin:/inter/bofbegin
    restart: always
