version: "3.6"
services:
    mysql_sql_level2:
        build: ./db
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
        restart: unless-stopped
        expose:
            - 3306
        environment:
            - MYSQL_ROOT_PASSWORD=vku_root_password_not_hacking
            - MYSQL_DATABASE=sql_level2
            - MYSQL_USER=vku
            - MYSQL_PASSWORD=vku_root_password_not_hacking

    sql-level2:
        build: ./
        restart: unless-stopped
        ports:
            - 8082:80
        volumes:
            - ./src:/var/www/html
        environment:
            - MYSQL_HOSTNAME=mysql_sql_level2
            - MYSQL_ROOT_PASSWORD=vku_root_password_not_hacking
            - MYSQL_DATABASE=sql_level2
            - MYSQL_USER=vku
            - MYSQL_PASSWORD=vku_root_password_not_hacking