version: '3'

services:
  bof-begin:
    build:
      context: ./bof-begin/challenge
      dockerfile: Dockerfile
    ports:
      - "10001:1337"
    restart: always
    
  store-flag:
    build:
      context: ./christmas-store/challenge
      dockerfile: Dockerfile
    ports:
      - "10002:1337"
    restart: always

  integer-overflow:
    build:
      context: ./integer-overflow/challenge
      dockerfile: Dockerfile
    ports:
      - "10004:1337"
    restart: always

  ret2win:
    build:
      context: ./ret2win/challenge
      dockerfile: Dockerfile
    ports:
      - "10003:1337"
    restart: always
  