version: '3'

services:
  bof-begin:
    build:
      context: ./bof-begin/challenge
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./bof-begin/challenge/src/flag.txt:/flag.txt
      - ./bof-begin/challenge/src/bofbegin:/bof/bofbegin
    restart: always
    
  store-flag:
    build:
      context: ./store-flag/challenge
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    volumes:
      - ./christmas-store/challenge/src/flag.txt:/flag.txt
      - ./christmas-store/challenge/src/ChristmasStore:/challengeStore/ChristmasStore
    restart: always

  ret2win:
    build:
      context: ./ret2win/challenge
      dockerfile: Dockerfile
    ports:
      - "1339:1339"
    volumes:
      - ./ret2win/challenge/src/flag.txt:/flag.txt
      - ./ret2win/challenge/src/ret2win:/ret2win/ret2win
    restart: always
  
  integer-overflow:
    build:
      context: ./integer-overflow/challenge
      dockerfile: Dockerfile
    ports:
      - "1340:1340"
    volumes:
      - ./integer-overflow/challenge/src/flag.txt:/integer/flag.txt
      - ./integer-overflow/challenge/src/overload:/integer/overload
    restart: always