version: '3'

services:
  bof-begin:
    build:
      context: ./bof-begin
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./bof-begin/src/flag.txt:/flag.txt
      - ./bof-begin/src/bofbegin:/bof/bofbegin
    restart: always
    
  store-flag:
    build:
      context: ./store-flag
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    volumes:
      - ./store-flag/src/flag.txt:/store/flag.txt
      - ./store-flag/src/store:/store/store
    restart: always

  ret2win:
    build:
      context: ./ret2win
      dockerfile: Dockerfile
    ports:
      - "1339:1339"
    volumes:
      - ./ret2win/src/flag.txt:/ret2win/flag.txt
      - ./ret2win/src/ret2win:/ret2win/ret2win
    restart: always
  
  integer-overflow:
    build:
      context: ./integer-overflow
      dockerfile: Dockerfile
    ports:
      - "1340:1340"
    volumes:
      - ./integer-overflow/src/flag.txt:/inter/flag.txt
      - ./integer-overflow/src/overload:/inter/overload
    restart: always